### ISSUE TITLE
/rate command: add the ability to estimate what stats an item will have at any given Chaos Tier

### ISSUE THREAD

**Issue by hyw-ell** [Cryotalis/Protobot-TS#1]
Though it is easy to calculate and make an estimation of what stats an item will have, many people don't know how to do this. Having this feature should make it much easier to calculate and estimate what stats an item will have when upgraded or downgraded.

**Comment by Intasa** [comment]
/rate should probably have the min stat as a requirement rather than an option since just doing `your stat/max stat` would assume 0
